# Server 실행 명령어 (Port option)
# java : java -jar user-service-0.0.1-SNAPSHOT.jar --server.port=9003
# maven : mvn spring-boot:run -Dspring-boot.run.jvmArguments='-Dserver.port=9004'

# 0인 경우 random port 설정
server:
  port: 0

spring:
  application:
    name: user-service

# 유레카 클라이언트 등록
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
