# Server 실행 명령어 (Port option)
# java 1 : java -jar order-service-0.0.1-SNAPSHOT.jar --server.port=9003
# java 2 : java -jar '-Dserver.port=8092' order-service-0.0.1-SNAPSHOT.jar
# maven : mvn spring-boot:run -Dspring-boot.run.jvmArguments='-Dserver.port=9004'

# 0인 경우 random port 설정
server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    # driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:testdb
    # username: sa
    url: jdbc:mariadb://localhost:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1q2w3e4r!

  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    # generate-ddl: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

# 유레카 클라이언트 등록
eureka:
  instance:
    hostname: localhost # temp
    # 랜덤포트로 동일 어플리케이션을 여러 개 실행하여도, 유레카 서버에서 인스턴스는 한 개만 보이기 때문에 instance id 부여
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.study.order_service: DEBUG
