server:
  port: 8888 # default

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://D:/workspace/micro-service-config
#          uri: https://github.com/opopqkr/micro-service.git
#          username:
#          password:
          default-label: main # If not set, the default is 'master branch'
