server:
  port: 8888 # default

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin1!
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            search-locations: file:///D:/workspace/micro-service-native-file
        git:
          uri: https://github.com/opopqkr/micro-service-config.git
#          username:
#          password:
#          uri: file://D:/workspace/micro-service-config
          default-label: main # If not set, the default is 'master branch'

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh