server:
  port: 8000

eureka:
  instance:
    hostname: localhost # temp
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        # - id: user-service
        #   uri: lb://USER-SERVICE
        #   predicates:
        #     - Path=/user-service/** # default request to user service ex) http://localhost:8081/user-service/**
        - id: user-service # 로그인을 위한 설정
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie # 매번 새로운 요청으로 인식하기 위해서 Header Cookie 삭제
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service # 회원가입을 위한 설정
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie # 매번 새로운 요청으로 인식하기 위해서 Header Cookie 삭제
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie # 매번 새로운 요청으로 인식하기 위해서 Header Cookie 삭제
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter # 회원가입, 로그인을 제외한 경우에는 모두 인증 체크
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/** # default request to user service ex) http://localhost:8081/user-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/** # default request to user service ex) http://localhost:8081/user-service/**
        - id: first-service
          # uri: http://localhost:8081/
          uri: lb://MY-FIRST-SERVICE # Obtain URI information through Eureka server
          predicates:
            - Path=/first-service/** # default request to first service ex) http://localhost:8081/first-service/**
          filters:
            # - AddRequestHeader=first-request, first-request-header2
            # - AddResponseHeader=first-response, first-response-header2
            - CustomFilter
        - id: second-service
          # uri: http://localhost:8082/
          uri: lb://MY-SECOND-SERVICE # Obtain URI information through Eureka server
          predicates:
            - Path=/second-service/** # default request to second service ex) http://localhost:8082/second-service/**
          filters:
            # - AddRequestHeader=second-request, second-request-header2
            # - AddResponseHeader=second-response, second-response-header2
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, there. This is Logging Filter.
                preLogger: true
                postLogger: true

token:
  secret: secret_token